# Unique name for this workflow
name: Scratch Org Validation

# Definition when the workflow should run
on:
    workflow_dispatch:
    push:
        branches:
            - 'main'

# Jobs to be executed .
jobs:
    scratch-org-validation:
        name: Scratch Org Validation
        runs-on: ubuntu-latest
        env:
            SCRATCH_NAME: ${{ github.event.repository.name }}
        steps:
            -   uses: actions/setup-node@v3
                with:
                    node-version: 19

            # Install Salesforce CLI.
            -   name: 'Install Salesforce CLI'
                run: | 
                    npm install sfdx-cli@7.204.6 --global
                    npm install @salesforce/cli --global

            # Install sfdx plugin
            -   name: 'Install plugin'
                shell: bash
                run: |
                    printf 'y\n' | sfdx plugins:install ci-sfdx-plugin@latest
                    printf 'y\n' | sfdx plugins:install sfdmu@latest

            # Obtain JWT certificate for DEVHUB
            -   name: 'Obtain JWT certificate from secrets'
                env:
                    JWT: ${{ secrets.DEV_HUB_CERTIFICATE }}
                shell: bash
                run: echo "$JWT" | base64 --decode > ${HOME}/server.key

            # Authenticate dev hub
            -   name: 'Authenticate Dev Hub'
                env:
                    SFDX_PATH: 'https://login.salesforce.com'
                    SF_USERNAME: 'devhub2@sejkorasvata.com'
                shell: bash
                run: sf org login jwt --client-id ${{ secrets.DEV_HUB_CLIENT_ID_KEY}} --jwt-key-file ${HOME}/server.key --instance-url $SFDX_PATH --username $SF_USERNAME --set-default-dev-hub --alias DevHub

            # Checkout the source code
            -   name: Checkout source code
                uses: actions/checkout@v3

            # Check org list
            - name: 'Check org list'
              run: |
                sf org list
                sf version --verbose --json

            # Create scratch org and push
            -   name: 'Create scratch org and push'
                run: |
                    sf org create scratch --set-default --definition-file config/project-scratch-def.json --alias test --duration-days 1 --wait 15

            # Check org list
            - name: 'Check org list'
              run: sf org list

            # Create user
            - name: 'Create user'
              run: sf org create user --set-alias sales --definition-file config/SalesUser.json --target-org test

            # Delete scratch org
            -   name: 'Delete scratch org'
                if: always()
                run: sfdx org delete scratch -p -o test